# Generated by Django 2.2.2 on 2019-10-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('Available', 'item ready to be prushase'), ('Sold', 'item has been sold'), ('restoking', 'item is restoking in few days')], default='Available', max_length=15)),
                ('issue', models.CharField(default='No Issues', max_length=100)),
                ('image', models.ImageField(upload_to='desktop_pic')),
            ],
            options={
                'ordering': (),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('Available', 'item ready to be prushase'), ('Sold', 'item has been sold'), ('restoking', 'item is restoking in few days')], default='Available', max_length=15)),
                ('issue', models.CharField(default='No Issues', max_length=100)),
                ('image', models.ImageField(upload_to='Laptops_pic')),
            ],
            options={
                'ordering': (),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('Available', 'item ready to be prushase'), ('Sold', 'item has been sold'), ('restoking', 'item is restoking in few days')], default='Available', max_length=15)),
                ('issue', models.CharField(default='No Issues', max_length=100)),
                ('image', models.ImageField(upload_to='mobiles_pic')),
            ],
            options={
                'ordering': (),
                'abstract': False,
            },
        ),
    ]
