# Generated by Django 2.2.2 on 2019-10-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desktop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mobile',
            options={},
        ),
    ]
