# Generated by Django 2.2.2 on 2019-10-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_auto_20191026_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.FileField(upload_to='Laptops_pic'),
        ),
    ]
