# Generated by Django 2.2.2 on 2019-10-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_auto_20191026_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(upload_to='Laptops_pic'),
        ),
    ]
