# Generated by Django 2.2.6 on 2019-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0004_auto_20191026_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='name_of_class',
            field=models.CharField(blank=True, default='Mobile', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='name_of_class',
            field=models.CharField(blank=True, default='Laptop', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='name_of_class',
            field=models.CharField(blank=True, default='Desktop', max_length=20, null=True),
        ),
    ]
