# Generated by Django 2.1.2 on 2019-11-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20191115_1720'),
        ('invent', '0005_auto_20191027_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='id',
        ),
        migrations.AddField(
            model_name='desktop',
            name='barcode',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='desktop',
            name='emp_init',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='desktop',
            name='fill',
            field=models.CharField(choices=[('chromeX15Laptop', '4'), ('OMENX2S15Laptop', '5')], default='chromeX15Laptop', max_length=13),
        ),
        migrations.AddField(
            model_name='desktop',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='serial_number',
            field=models.CharField(default='00', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='barcode',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='emp_init',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='fill',
            field=models.CharField(choices=[('HuaweiP', 'HuaweiP20'), ('Huawei', 'HuaweiY9Prime2019')], default='HuaweiP20', max_length=3),
        ),
        migrations.AddField(
            model_name='mobile',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='serial_number',
            field=models.CharField(default='00', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='size',
            field=models.CharField(choices=[('T', 'T'), ('K', 'K'), ('S', 'S'), ('D', 'D'), ('Q', 'Q'), ('R', 'R'), ('50', '50'), ('40', '40'), ('20', '20'), ('15', '15'), ('10', '10'), ('5', '5'), ('2.5', '2.5')], default='T', max_length=3),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('chromeX15Laptop', 'chromeX15Laptop'), ('OMENX2S15Laptop', 'OMENX2S15Laptop')], default='chromeX15Laptop', max_length=2),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('HuaweiP', 'HuaweiP'), ('Huawei', 'Huawei')], default='HuaweiP', max_length=2),
        ),
    ]
