# Generated by Django 2.1.2 on 2019-11-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0009_auto_20191115_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='barcode',
        ),
    ]
