# Generated by Django 2.1.2 on 2019-11-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0010_remove_mobile_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='barcode',
        ),
    ]
