# Generated by Django 2.1.2 on 2019-11-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0011_remove_desktop_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='barcode',
            field=models.CharField(default='Desktop', max_length=15),
        ),
        migrations.AddField(
            model_name='mobile',
            name='barcode',
            field=models.CharField(default='HuaweiP20', max_length=15),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='name_of_class',
            field=models.CharField(blank=True, default='Desktop', max_length=20, null=True),
        ),
    ]
