# Generated by Django 2.1.2 on 2019-11-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0012_auto_20191115_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='desktop',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='desktop',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desktop',
            name='fill',
            field=models.CharField(choices=[('HP', 'HP'), ('asus', 'asus')], default='asus', max_length=13),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('HP', 'HP'), ('asus', 'asus')], default='asus', max_length=2),
        ),
    ]
