# Generated by Django 2.1.2 on 2019-11-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0013_auto_20191117_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='fill',
            field=models.CharField(choices=[('HP', 'HP'), ('asus', 'asus')], max_length=13),
        ),
    ]
