# Generated by Django 2.1.2 on 2019-11-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_auto_20191117_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='fill',
            field=models.CharField(choices=[('HuaweiP', 'HuaweiP20'), ('Huawei', 'HuaweiY9Prime2019')], default='HuaweiP20', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('HuaweiP', 'HuaweiP'), ('Huawei', 'Huawei')], default='HuaweiP', max_length=10),
        ),
    ]
