# Generated by Django 2.1.2 on 2019-11-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedDesktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill', models.CharField(choices=[('chromeX15Laptop', '4'), ('OMENX2S15Laptop', '5')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='QueuedMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill', models.CharField(choices=[('HuaweiP', 'HuaweiP20'), ('Huawei', 'HuaweiY9Prime2019')], max_length=13)),
                ('size', models.CharField(choices=[('T', 'T'), ('K', 'K'), ('S', 'S'), ('D', 'D'), ('Q', 'Q'), ('R', 'R'), ('50', '50'), ('40', '40'), ('20', '20'), ('15', '15'), ('10', '10'), ('5', '5'), ('2.5', '2.5')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='queuedbottle',
            name='order',
        ),
        migrations.RemoveField(
            model_name='queuedtub',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='emp_init',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='QueuedBottle',
        ),
        migrations.DeleteModel(
            name='QueuedTub',
        ),
        migrations.AddField(
            model_name='queuedmobile',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
        migrations.AddField(
            model_name='queueddesktop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
    ]
