# Generated by Django 2.1.2 on 2019-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20191115_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueddesktop',
            name='fill',
            field=models.CharField(choices=[('chromeX15Laptop', 'chromeX15Laptop'), ('OMENX2S15Laptop', 'OMENX2S15Laptop')], max_length=13),
        ),
    ]
