# Generated by Django 2.1.2 on 2019-11-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20191117_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueddesktop',
            name='fill',
            field=models.CharField(choices=[('HP', 'HP'), ('asus', 'asus')], max_length=13),
        ),
    ]
